server:
  port: 8888

spring:
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

cloud:
  config:
    server:
      git:
        uri: https://github.com/JairoIxiss/sistesma-tienda-electrodomesticos.git
        searchPaths: config-data
        username: ${GIT_USER}
        password: ${GIT_PASSWORD}